apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-certificate
  namespace: "{{app_namespace}}"
spec:
  secretName: tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "{{domain_name}}"
  dnsNames:
  - "{{domain_name}}"