- name: Create namespace
  k8s:
    state: present
    definition: "{{ lookup('template', 'namespace.yaml') }}"
- name: deploy front
  vars:
    frontend_docker_tag: "latest"
  k8s:
    state: present
    definition: "{{ lookup('template', 'front.yaml') }}"
    namespace: "{{ app_namespace }}"
- name: deploy back
  vars:
    backend_docker_tag: "latest"
  k8s:
    state: present
    definition: "{{ lookup('template', 'back.yaml') }}"
    namespace: "{{ app_namespace }}"